export const MAKE_MOVE_REQUESTED = "MAKE_MOVE_REQUESTED";
export const MAKE_MOVE_SUCCEEDED = "MAKE_MOVE_SUCCEEDED";
export const MAKE_MOVE_FAILED = "MAKE_MOVE_FAILED";

export const SELECT_SQUARE = "SELECT_SQUARE"